#!/bin/bash

# Test to see if user is running with root privileges.
if [[ "${UID}" -ne 0 ]]
then
 echo 'Must execute with sudo or root' >&2
 exit 1
fi

# Update and Upgrade System
apt update -y
apt upgrade -y

# Install necessary packages
apt install wget screen -y

# Download and Install the latest version of Java
JAVA_URL=$(wget -qO- https://jdk.java.net/ | grep -oP 'https://download.java.net/java/GA/jdk[0-9]+.[0-9]+.[0-9]+/\K[^"]+')
wget -O java_latest.tar.gz $JAVA_URL
tar xvf java_latest.tar.gz
mv jdk-* /opt/jdk_latest

tee /etc/profile.d/jdk.sh <<EOF
export JAVA_HOME=/opt/jdk_latest
export PATH=\$PATH:\$JAVA_HOME/bin
EOF

source /etc/profile.d/jdk.sh
java -version
rm java_latest.tar.gz

# Download the latest version of Minecraft Server
wget -O server.jar https://launcher.mojang.com/mc/game/version_manifest.json | jq -r '.latest.release' | xargs -I {} wget -O server.jar https://launcher.mojang.com/v1/objects/$(wget -qO- https://launchermeta.mojang.com/mc/game/version_manifest.json | jq -r --arg version "{}" '.versions[] | select(.id == $version) | .url')/server.jar

# Create Minecraft directory and move server.jar
mkdir -p Minecraft
mv server.jar Minecraft/
cd Minecraft

# Create start script
echo "java -Xms1024M -Xmx2560M -jar server.jar nogui" > start.sh
chmod +x start.sh

# Accept EULA
echo "eula=true" > eula.txt

# Start Minecraft Server
screen ./start.sh
